server:
  port: 8763

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Spring
spring:
  application:
    name: godzilla-oauth
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/godzilla_oauth?characterEncoding=utf8&useUnicode=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=Shanghai
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.cj.jdbc.Driver #mysql 6.0以上使用该链接
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 20
      min-idle: 8
      initial-size: 10
      minEvictable-idle-time-millis: 40000
      filters: stat,wall,log4j

  redis: #Redis配置，单机模式
    host: 127.0.0.1 #配置集群时需要注释掉host属性
    port: 6379
    password: 123
    #sentinel: #redis哨兵模式配置
    #  master:mymaster
    #  nodes=192.168.3.15:6380,1192.168.3.15:6381,192.168.3.15:6382
    #cluster: #集群模式
    #  nodes: 192.168.3.15:6380,1192.168.3.15:6381,192.168.3.15:6382
#mybatis mapper xml文件路径配置
mybatis:
  type-aliases-package: com.adwyxx.godzilla.oauth.mapper #mybatis mapper对应的实体包名配置
  mapper-locations: classpath:com.adwyxx.oauth.mapper/*.xml

#Druid后台用户名密码
druid:
  username: admin
  password: 123
