# redisson config
#masterSlaveServersConfig: #主从模式配置
#sentinelServersConfig: #哨兵模式配置
#clusterServersConfig: #集群模式配置
#replicatedServersConfig: #云托管模式配置
singleServerConfig: #单机模式配置
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000 #命令等待超时，单位：毫秒.等待节点回复命令的时间。该时间从命令发送成功时开始计时。
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1 #发布和订阅连接的最小空闲连接数.Redisson内部经常通过发布和订阅来实现许多功能。长期保持一定数量的发布订阅连接是必须的。
  subscriptionConnectionPoolSize: 50 #发布和订阅连接池大小
  connectionMinimumIdleSize: 32 #最小空闲连接数
  connectionPoolSize: 64
  database: 0 #数据库编号
  dnsMonitoring: false #是否启用DNS监测
  dnsMonitoringInterval: 5000 #DNS监测时间间隔，单位：毫秒
  clientName: null #客户端名称,在Redis节点里显示的客户端名称
  password: "123"
  #---单机模式配置----#
  address: "redis://127.0.0.1:6379"  #节点地址
  #---主从模式配置----#
  #readMode: "SLAVE"
  #sentinelAddresses:
  #- "redis://127.0.0.1:26379"
  #- "redis://127.0.0.1:26389"
  #masterName: "mymaster"
  #---哨兵模式配置----#
  #readMode: "SLAVE"
  #sentinelAddresses:
  #- "redis://127.0.0.1:26379"
  #- "redis://127.0.0.1:26389"
  #masterName: "mymaster"
  #---集群模式配置----#
  #readMode: "SLAVE"
  #nodeAddresses:
  #- "redis://127.0.0.1:7004"
  #- "redis://127.0.0.1:7001"
  #- "redis://127.0.0.1:7000"
threads: 0 #Netty线程池数量.默认值: 当前处理核数量 * 2
nettyThreads: 0 #Netty线程池数量.默认值: 当前处理核数量 * 2
#编码,Redisson的对象编码类是用于将对象进行序列化和反序列化，以实现对该对象在Redis里的读取和存储
codec: #!<org.redisson.codec.JsonJacksonCodec> {}
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO" #传输模式,默认值：TransportMode.NIO